services:
  manager:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ROLE=MANAGER
    volumes:
      - ./result.json:/root/result.json 
    networks:
      - cluster-net

  worker:
    build: .
    depends_on:
      - manager
    environment:
      - ROLE=WORKER
      - JOIN_ADDR=manager:7946
    deploy:
      replicas: 3
    networks:
      - cluster-net


networks:
  cluster-net:
    driver: bridge