package main

import (
	"fmt"
	"github.com/omar/distributed-cracker/proto"
)

func main() {
	// Creating a TaskRequest using the code generated by buf/protoc
	task := &proto.TaskRequest{
		TargetHash: "5f4dcc3b5aa765d61d8327deb882cf99",
		StartRange: "aaaa",
		EndRange:   "zzzz",
		Alphabet:   "abcdefghijklmnopqrstuvwxyz",
	}

	fmt.Printf("Successfully created gRPC TaskRequest!\n")
	fmt.Printf("Target Hash: %s\n", task.TargetHash)
	fmt.Printf("Range: %s to %s\n", task.StartRange, task.EndRange)
}