// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/cracker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CrackerService_ProcessTask_FullMethodName = "/cracker.CrackerService/ProcessTask"
)

// CrackerServiceClient is the client API for CrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrackerServiceClient interface {
	// The Manager calls this on the Worker
	ProcessTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
}

type crackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrackerServiceClient(cc grpc.ClientConnInterface) CrackerServiceClient {
	return &crackerServiceClient{cc}
}

func (c *crackerServiceClient) ProcessTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, CrackerService_ProcessTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrackerServiceServer is the server API for CrackerService service.
// All implementations must embed UnimplementedCrackerServiceServer
// for forward compatibility
type CrackerServiceServer interface {
	// The Manager calls this on the Worker
	ProcessTask(context.Context, *TaskRequest) (*TaskResponse, error)
	mustEmbedUnimplementedCrackerServiceServer()
}

// UnimplementedCrackerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCrackerServiceServer struct {
}

func (UnimplementedCrackerServiceServer) ProcessTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTask not implemented")
}
func (UnimplementedCrackerServiceServer) mustEmbedUnimplementedCrackerServiceServer() {}

// UnsafeCrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrackerServiceServer will
// result in compilation errors.
type UnsafeCrackerServiceServer interface {
	mustEmbedUnimplementedCrackerServiceServer()
}

func RegisterCrackerServiceServer(s grpc.ServiceRegistrar, srv CrackerServiceServer) {
	s.RegisterService(&CrackerService_ServiceDesc, srv)
}

func _CrackerService_ProcessTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrackerServiceServer).ProcessTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrackerService_ProcessTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrackerServiceServer).ProcessTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrackerService_ServiceDesc is the grpc.ServiceDesc for CrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cracker.CrackerService",
	HandlerType: (*CrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessTask",
			Handler:    _CrackerService_ProcessTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cracker.proto",
}
